spring.datasource.url=jdbc:postgresql://dpg-d7fq91po3t8c7381jhhg-a.frankfurt-postgres.render.com:5432/bikerent_055f?sslmode=require
spring.datasource.username=bikerentdb_6rld_user
spring.datasource.password=YRTwl0KTXAye52YrxZq6u0FJRw4FLEyi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.cache=false